name: Create GitHub Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch all history for changelog generation if needed

    - name: Read Changelog
      id: changelog
      run: |
        CHANGELOG_CONTENT=$(cat CHANGELOG.md)
        # Escape newlines and quotes for JSON
        echo "changelog_body<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG_CONTENT" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: ${{ steps.changelog.outputs.changelog_body }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
